More Information Required:
    - '^((?!Steps to reproduce)[\s\S])*$|^((?!Repository to reproduce)[\s\S])*$|^((?!Expected result)[\s\S])*$|^((?!Actual result)[\s\S])*$|^((?!CLI Version)[\s\S])*$|^((?!plugin Version)[\s\S])*$|^((?!OS)[\s\S])*$'
