#
# Copyright (c) 2020, salesforce.com, inc.
# All rights reserved.
# Licensed under the BSD 3-Clause license.
# For full license text, see LICENSE.txt file in the repo root or https://opensource.org/licenses/BSD-3-Clause
#

name: "new-label"
on: # any labels added to an issue
  issues:
    types: [labeled]

jobs:
  owned-by-other-team:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.0.0 
    - name: issue comment
      id: issue_comment
      uses: ./
      with: 
        repo-token: ${{ secrets.GITHUB_TOKEN}}
        label: 'owned by another team'
        message: >
          We have determined that the issue you reported exists in code owned by another team that uses only the official support channels.
          To ensure that your issue is addressed, open an official Salesforce customer support ticket with a link to this issue.
          We encourage anyone experiencing this issue to do the same to increase the priority. We will keep this issue open for the community to collaborate on.

    - name: log action output
      run: echo ${{steps.run_action.outputs.message}}     
  other-thing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.0.0 
    - name: issue comment
      id: issue_comment
      uses: ./
      with: 
        repo-token: ${{ secrets.GITHUB_TOKEN}}
        label: 'More Information Required'
        message: >
          Your issue is missing required information from the [bug template](https://github.com/forcedotcom/cli/blob/main/.github/ISSUE_TEMPLATE/bug_report.md). When you provide us this information we'll triage and reproduce the issue.
    - name: log action output
      run: echo ${{steps.run_action.outputs.message}}     
  default:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.0.0 
    - name: issue comment
      id: issue_comment
      uses: ./
      with: 
        repo-token: ${{ secrets.GITHUB_TOKEN}}
        message: >
          Thank you for filling this issue.  We appreciate your feedback and will review the issue as soon as possible. 
            Remember, however, that GitHub isn't a mechanism for receiving support under any agreement or SLA. 
            If you require immediate assistance, contact Salesforce Customer Support.
    - name: log action output
      run: echo ${{steps.run_action.outputs.message}}     
